### ISSUE TITLE
Some Confusion in Understanding Code About Survival Function

### ISSUE THREAD

**Issue by DylanMingan** [haoy945/JacksCarRental#1]
Hello, Dear haoy945
I am a newbie in Reinforcement learning. I was very excited when I found your exquisite, concise, and effective code about JacksCarRental. But unfortunately, my personal ability does not support me to fully understand your code. Following is my confusion.

**1.Why we need a survival function, and its parameters are n-1？**
` poisson_prob[i, n, 1] = poisson.sf(n-1, m)`

**2.Why use the survival function when a1 = = ss1，a2==ss2...?**
`prob_a1 = PoissonProb[1, a1, int(a1 == ss1)]`
`        prob_a2 = PoissonProb[2, a2, int(a2 == ss2)]
`
`            prob_b1 = PoissonProb[1, b1, int(b1 == b1_bound-1)]
`
`            prob_b2 = PoissonProb[0, b2, int(b2 == b2_bound-1)]`

Many Thanks! Looking forward to your reply!

**Comment by haoy945** [comment]
Hi, below is my answer.

#### 1.We need to use survival function in the following two situations：
 - When a1 >= ss1, we can only rent out ss1 cars. The probability of this occurrence is P(a1 >= ss1), which is the survival function.
 - When b1 >= 20-ss1+a1, we can only get 20-ss1+a1 cars since we assume that there can be no more than 20 cars at each location. The probability of this occurrence is P(b1 >= 20-ss1+a1), which is also the survival function.

Since P(x>=n)=P(x>n-1)=`poisson.sf(n-1, m)`, we use n-1 as the parameters.

#### 2.We just use `a1 == ss1` as a sign of a1 >= ss1 and its probability is just the survival function...

Hope this answer can help you.

**Comment by DylanMingan** [comment]
> Hi, below is my answer.
> 
> #### 1.We need to use survival function in the following two situations：
> * When a1 >= ss1, we can only rent out ss1 cars. The probability of this occurrence is P(a1 >= ss1), which is the survival function.
> * When b1 >= 20-ss1+a1, we can only get 20-ss1+a1 cars since we assume that there can be no more than 20 cars at each location. The probability of this occurrence is P(b1 >= 20-ss1+a1), which is also the survival function.
> 
> Since P(x>=n)=P(x>n-1)=`poisson.sf(n-1, m)`, we use n-1 as the parameters.
> 
> #### 2.We just use `a1 == ss1` as a sign of a1 >= ss1 and its probability is just the survival function...
> Hope this answer can help you.

It helps. Thank you from the bottom of my heart for your kind help!!!
